version: '3'
services:
  server-app:
    restart: always
    env_file: .env
    container_name: web_server
    image: project
    ports:
      - "5005:5005"
    depends_on:
      - mysql-app
    networks:
      - project_netowrk

  mysql-app:
    restart: always
    container_name: mysql_server
    image: mysql:5.7
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 23306:3306
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ALLOW_EMPTY_PASSWORD: 'True'
    networks:
      - project_netowrk
networks:
  project_netowrk:
    name: project_netowrk
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.1/16